import { it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import ExcelJS from 'exceljs';
import { buildWorkbook, textChunks } from './export';
import type { Dataset } from './types';
const selection = { planId: 'luna-highscore-v1', baseline: 'generation_security_none', condition: 'generation_security_all', suite: 'security' };
it('exports individual test contracts, missing rates and exact prompts without old runs', async () => {
  const data: Dataset = JSON.parse(await readFile('public/data/study.json', 'utf8'));
  const wb = await buildWorkbook(data, selection, a => readFile(`public/${a.href}`));
  expect(wb.getWorksheet('Runs')!.rowCount).toBe(1);
  expect(wb.getWorksheet('Check observations')!.rowCount).toBe(1);
  expect(wb.getWorksheet('Test comparisons')!.rowCount).toBe(12);
  expect(wb.getWorksheet('Test definitions')!.rowCount).toBe(28);
  expect(wb.getWorksheet('Context records')!.rowCount).toBe(146);
  const rates = wb.getWorksheet('Test comparisons')!;
  expect(rates.getRow(2).getCell('baseline_passRate').value).toBeNull();
  expect(rates.getRow(2).getCell('delta_pp').value).toBeNull();
  const prompt = data.experimentPlans[0].conditions.find(c => c.id === selection.condition)!.prompt;
  let text = '';
  wb.getWorksheet('Evidence text')!.eachRow((row, i) => { if (i > 1 && row.getCell('sha256').value === prompt.sha256) text += row.getCell('text').value; });
  expect(text).toBe(await readFile(`public/${prompt.href}`, 'utf8'));
  wb.getWorksheet('Read me')!.addRow({ field: 'formula_test', value: '=HYPERLINK("https://invalid.example","x")' });
  const loaded = new ExcelJS.Workbook(); await loaded.xlsx.load(await wb.xlsx.writeBuffer());
  expect(loaded.getWorksheet('Read me')!.lastRow!.getCell(2).type).toBe(ExcelJS.ValueType.String);
}, 30000);
it('preserves long Unicode and refuses corrupted artifacts', async () => {
  const text = 'a'.repeat(29999) + '🧪' + 'z'.repeat(40000);
  expect(textChunks(text).join('')).toBe(text);
  expect(textChunks(text)[0]).toHaveLength(29999);
  const data: Dataset = JSON.parse(await readFile('public/data/study.json', 'utf8'));
  await expect(buildWorkbook(data, selection, async () => new Uint8Array([1]))).rejects.toThrow('Evidence hash mismatch');
});
