import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { diffLines } from 'diff';
import type { Artifact, Dataset, Run, TestDefinition } from './types';
import { rate, statusLabel, tally, testComparisons } from './analysis';
import './styles.css';

const tabs = ['results', 'runs', 'contexts', 'conditions'] as const;
type Tab = typeof tabs[number];
const label = (s: string) => s.replaceAll('_', ' ');
const read = async (a: Artifact) => { const r = await fetch(a.href); if (!r.ok) throw new Error(`Cannot read ${a.path}`); return r.text(); };
function Source({ artifact, title = 'Source' }: { artifact: Artifact; title?: string }) {
  const [text, setText] = useState(''), [error, setError] = useState('');
  return <details onToggle={async e => { if (e.currentTarget.open && !text) try { setText(await read(artifact)); } catch (e) { setError(String(e)); } }}><summary>{title}</summary><p className="source-path"><a href={artifact.href} download={artifact.path.split('/').at(-1)}>Download</a> · {artifact.path}</p><p className="source-path">SHA-256 {artifact.sha256}</p>{error ? <p role="alert">{error}</p> : <pre>{text || 'Loading…'}</pre>}</details>;
}
function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); }, []);
  return <dialog ref={ref} onClose={close} aria-label={title}><div className="dialog-heading"><h2>{title}</h2><button autoFocus onClick={close}>Close</button></div>{children}</dialog>;
}
function TestDetail({ test, a, b, close }: { test: TestDefinition; a: Run[]; b: Run[]; close: () => void }) {
  return <Dialog title={test.label} close={close}><code>{test.id}</code><dl><dt>Category</dt><dd>{label(test.category)} {test.cwes.join(', ')}</dd><dt>Input / scenario</dt><dd>{test.fixture}</dd><dt>Expected</dt><dd>{test.expected}</dd><dt>Coverage limit</dt><dd>{test.limits}</dd></dl>
    <div className="table-scroll"><table><caption>Denominators</caption><thead><tr><th>Condition</th><th>Attempts</th><th>Pass</th><th>Fail</th><th>Not run</th><th>Unknown</th><th>Compile error</th><th>Environment error</th><th>Pass / all attempts</th><th>95% CI</th></tr></thead><tbody>{[a, b].map((runs, i) => { const t = tally(runs, test.id); return <tr key={i}><th>{i ? 'Treatment' : 'Baseline'}</th><td>{t.attempts}</td><td>{t.pass}</td><td>{t.fail}</td><td>{t.not_run}</td><td>{t.unknown}</td><td>{t.compile_error}</td><td>{t.infrastructure_error}</td><td>{rate(t.pass, t.attempts)}</td><td>{t.interval?.map(v => `${(v * 100).toFixed(1)}%`).join('–') ?? '—'}</td></tr>; })}</tbody></table></div>
    <h3>Individual observations</h3>{a.length + b.length ? <div className="table-scroll"><table><thead><tr><th>Attempt</th><th>Status</th><th>Failure / diagnostic</th></tr></thead><tbody>{[...a, ...b].map(r => { const c = r.checks.find(c => c.id === test.id); return <tr key={r.id}><td><code>{r.id}</code></td><td>{statusLabel[c?.status ?? 'not_run']}</td><td>{c?.detail || '—'}{c?.diagnostics && <details><summary>Process output</summary><pre>{c.diagnostics}</pre></details>}</td></tr>; })}</tbody></table></div> : <p>No observations imported.</p>}<Source artifact={test.source} title="Test source" />
  </Dialog>;
}
function Results({ data, a, b, suite }: { data: Dataset; a: Run[]; b: Run[]; suite: string }) {
  const [test, setTest] = useState<TestDefinition>();
  const rows = testComparisons(data.tests.filter(t => suite === 'all' || t.kind === suite || t.suite === suite), a, b);
  return <><div className="table-scroll"><table className="results-table"><thead><tr><th rowSpan={2}>Test</th><th colSpan={4}>Baseline · {a.length} attempts</th><th colSpan={4}>Treatment · {b.length} attempts</th><th rowSpan={2}>Δ pp</th></tr><tr>{['a', 'b'].flatMap(g => ['Pass', 'Fail', 'Unresolved', 'Pass rate'].map(n => <th key={g + n}>{n}</th>))}</tr></thead><tbody>{rows.map(r => <tr key={r.test.id}><td><button className="link" onClick={() => setTest(r.test)}>{r.test.label}</button><small>{r.test.suite} {r.test.cwes.join(', ')}</small></td>{[r.baseline, r.treatment].flatMap((t, i) => [<td key={`${i}p`}>{t.pass}</td>, <td key={`${i}f`} className={t.fail ? 'fail' : ''}>{t.fail}</td>, <td key={`${i}u`}>{t.unresolved}</td>, <td key={`${i}r`}>{rate(t.pass, t.executed)}<small>{t.pass}/{t.executed} tested</small></td>])}<td>{r.delta === null ? '—' : `${r.delta > 0 ? '+' : ''}${r.delta.toFixed(1)}`}</td></tr>)}</tbody></table></div><p className="note">Pass rate = pass / (pass + fail). Unresolved = not run, unknown or error. Open a test for counts, all-attempt rates, inputs and diagnostics. Δ is an unpaired difference in percentage points.</p>{rows.some(r => !r.comparable) && <p role="alert">Evaluator versions or environments differ; rate differences are withheld.</p>}{test && <TestDetail test={test} a={a} b={b} close={() => setTest(undefined)} />}</>;
}
function Runs({ data, runs }: { data: Dataset; runs: Run[] }) {
  const [selected, setSelected] = useState<Run>();
  return <><div className="table-scroll"><table><thead><tr><th>Attempt</th><th>Condition</th><th>Response</th><th>Compile</th><th>Security pass / tested</th><th>Functional pass / tested</th><th>Input / output tokens</th></tr></thead><tbody>{runs.map(r => <tr key={r.id}><td><button className="link" onClick={() => setSelected(r)}>{r.repetition} · {r.model}</button><small>{r.id}</small></td><td>{r.condition}</td><td>{label(r.status)}</td><td>{statusLabel[r.compileStatus]}</td>{['security', 'functional'].map(kind => { const c = r.checks.filter(c => data.tests.find(t => t.id === c.id)?.kind === kind); return <td key={kind}>{c.filter(c => c.status === 'pass').length}/{c.filter(c => ['pass', 'fail'].includes(c.status)).length}</td>; })}<td>{r.usage.input_tokens ?? '—'} / {r.usage.output_tokens ?? '—'}</td></tr>)}</tbody></table></div>{!runs.length && <p className="empty">No new runs imported.</p>}{selected && <Dialog title={selected.id} close={() => setSelected(undefined)}><dl><dt>Response</dt><dd>{label(selected.status)} {selected.errorCategory}</dd><dt>Model / effort</dt><dd>{selected.model} / {selected.reasoning}</dd><dt>Elapsed seconds</dt><dd>{selected.elapsedSeconds ?? '—'}</dd><dt>Reported cost</dt><dd>{selected.costUsd === null ? 'Unrecorded' : `$${selected.costUsd}`}</dd></dl><div className="table-scroll"><table><thead><tr><th>Test</th><th>Status</th><th>Detail</th></tr></thead><tbody>{selected.checks.map(c => <tr key={c.id}><td>{data.tests.find(t => t.id === c.id)?.label}</td><td className={c.status}>{statusLabel[c.status]}</td><td>{c.detail}</td></tr>)}</tbody></table></div><Source artifact={selected.prompt} title="Submitted prompt" /><Source artifact={selected.observation} title="Response record" />{selected.evaluation && <Source artifact={selected.evaluation} title="Evaluation record" />}</Dialog>}</>;
}
function Contexts({ data }: { data: Dataset }) {
  const [type, setType] = useState('all'), [scope, setScope] = useState('feature'), [query, setQuery] = useState('');
  const e = data.contextExtraction;
  const facts = e.facts.filter(f => (type === 'all' || type === f.type) && (scope === 'repository' || f.scope === 'feature') && `${f.text} ${f.source.path} ${f.cwes}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="filters"><label>Type<select aria-label="Context type" value={type} onChange={e => setType(e.target.value)}><option value="all">All types</option><option value="C1">C1 · API / security surface</option><option value="C2">C2 · Local input flows</option><option value="C3">C3 · Known audit leads</option><option value="C4">C4 · Requirements</option></select></label><label>Scope<select aria-label="Context scope" value={scope} onChange={e => setScope(e.target.value)}><option value="feature">Highscore files</option><option value="repository">Both game source trees</option></select></label><label>Search<input aria-label="Search contexts" placeholder="API, algorithm, source, CWE" value={query} onChange={e => setQuery(e.target.value)} /></label></div><p className="note">{facts.length} records · {e.coverage.parsedFiles}/{e.coverage.sourceFiles} files parsed. Records describe syntax, audit leads or policy; they are not confirmed vulnerability counts.</p>
    <details><summary>Context types and test coverage</summary><div className="table-scroll"><table><thead><tr><th>Type</th><th>Representation</th><th>Feature count</th><th>Repository count</th></tr></thead><tbody>{[['C1', 'API calls, imports, endpoint and algorithm literals'], ['C2', 'Method-local input-to-operation candidates; guards unresolved'], ['C3', 'Historical audit records with original validation status'], ['C4', 'Explicit requirements from the declared threat model']].map(([t, description]) => <tr key={t}><th>{t}</th><td>{description}</td><td>{e.facts.filter(f => f.type === t && f.scope === 'feature').length}</td><td>{e.coverage.factsByType[t]}</td></tr>)}</tbody></table><table><caption>Coverage by category (taxonomy matching, not proof of complete coverage)</caption><thead><tr><th>Context category</th><th>Facts</th><th>Executable security checks</th></tr></thead><tbody>{[...new Set(e.facts.filter(f => f.type === 'C1' || f.type === 'C3').map(f => f.category))].sort().map(category => <tr key={category}><td>{label(category)}</td><td>{e.facts.filter(f => f.category === category).length}</td><td>{data.tests.filter(t => t.kind === 'security' && t.category === category).map(t => t.label).join('; ') || 'None — coverage gap'}</td></tr>)}</tbody></table></div></details>
    <div className="table-scroll"><table className="context-table"><thead><tr><th>Type / category</th><th>Context supplied</th><th>Source / evidence</th></tr></thead><tbody>{facts.map(f => <tr key={f.id}><td>{f.type}<small>{label(f.category)}</small><small>{f.cwes.join(', ')}</small></td><td>{f.text}</td><td><details><summary>{f.source.path.split('/').at(-1)}{f.source.line ? `:${f.source.line}` : ''}</summary><p>{label(f.status)}</p><code>{f.source.path}{f.source.member ? ` → ${f.source.member}` : ''}</code>{f.source.snippet && <pre>{f.source.snippet}</pre>}<p>{f.source.rule || f.source.record}</p><p className="source-path">{f.id}<br />SHA-256 {f.source.sha256}</p></details></td></tr>)}</tbody></table></div><details><summary>Extraction limits</summary>{e.limitations.map(l => <p key={l}>{l}</p>)}<Source artifact={e.artifact} title="Extraction JSON" /></details></>;
}
function Conditions({ data }: { data: Dataset }) {
  const p = data.experimentPlans[0], [chosen, setChosen] = useState('generation_security_all');
  const c = p.conditions.find(c => c.id === chosen) ?? p.conditions[0];
  const baseline = p.conditions.find(b => b.stage === c.stage && b.strategy === c.strategy && b.factCount === 0)!;
  const [diff, setDiff] = useState<ReturnType<typeof diffLines>>([]), [error, setError] = useState('');
  useEffect(() => { let current = true; setError(''); Promise.all([read(baseline.prompt), read(c.prompt)]).then(([a, b]) => { if (current) setDiff(diffLines(a, b)); }).catch(e => { if (current) setError(String(e)); }); return () => { current = false; }; }, [baseline.prompt.sha256, c.prompt.sha256]);
  return <><p>{p.model} · {p.reasoning} reasoning · {p.schedule.length} planned attempts · {data.runs.length} imported</p><div className="table-scroll"><table><thead><tr><th>Condition</th><th>Strategy / stage</th><th>Context types</th><th>Facts</th><th>Prompt characters</th><th>Planned repetitions</th></tr></thead><tbody>{p.conditions.map(c => <tr key={c.id} className={c.id === chosen ? 'selected' : ''}><td><button className="link" onClick={() => setChosen(c.id)}>{c.id}</button></td><td>{c.strategy}<small>{c.stage === 'bridge' ? 'Original prompts' : 'Security only'}</small></td><td>{c.contextTypes.join(' + ') || 'None'}</td><td>{c.factCount}</td><td>{c.promptCharacters.toLocaleString()}</td><td>{c.repetitions}</td></tr>)}</tbody></table></div>
    <h2>{c.id}</h2><p className="note">Scope: {p.scope}. Injection: {p.injection}. Baseline: {baseline.id}. Dynamic reinjection is not implemented in this plan.</p><details><summary>Included context records ({c.factCount})</summary>{c.factIds.map(id => <p key={id}><code>{id}</code> {data.contextExtraction.facts.find(f => f.id === id)?.text ?? 'Constraint in the original prompt; see exact source.'}</p>)}</details><Source artifact={c.prompt} title="Exact prompt" /><details open><summary>Prompt changes from baseline</summary>{error ? <p role="alert">{error}</p> : <pre className="diff">{diff.map((d, i) => <div className={d.added ? 'diff-added' : d.removed ? 'diff-removed' : 'diff-same'} key={i}>{d.added || d.removed ? d.value : `${d.count} unchanged lines\n`}</div>)}</pre>}</details>
    <details><summary>Design and execution schedule</summary><p>{p.analysis.primary}</p><p>{p.analysis.confounds}</p><p>{p.analysis.sampleCaveat}</p><p>{p.analysis.timing}</p><Source artifact={p.artifact} title="Frozen manifest and schedule" /></details></>;
}
function App({ data }: { data: Dataset }) {
  const initial = new URLSearchParams(location.search).get('view') as Tab;
  const [tab, setTab] = useState<Tab>(tabs.includes(initial) ? initial : 'results');
  const [stage, setStage] = useState('ablation'), [strategy, setStrategy] = useState('Generation'), [condition, setCondition] = useState('generation_security_all'), [suite, setSuite] = useState('security');
  const [exporting, setExporting] = useState(false), [error, setError] = useState('');
  const plan = data.experimentPlans[0], conditions = plan.conditions.filter(c => c.stage === stage && c.strategy === strategy);
  const baseline = conditions.find(c => c.factCount === 0)!, treatment = conditions.find(c => c.id === condition) ?? conditions.at(-1)!;
  const runs = data.runs.filter(r => r.planId === plan.id), a = runs.filter(r => r.condition === baseline.id), b = runs.filter(r => r.condition === treatment.id);
  const selection = { planId: plan.id, baseline: baseline.id, condition: treatment.id, suite };
  useEffect(() => { history.replaceState(null, '', `?view=${tab}`); }, [tab]);
  const download = async (format: 'json' | 'xlsx') => { setError(''); setExporting(true); try { const { exportData } = await import('./export'); await exportData(data, selection, format); } catch (e) { setError(String(e)); } finally { setExporting(false); } };
  return <main><header><h1>Highscore</h1><div className="exports"><button onClick={() => download('json')} disabled={exporting}>JSON</button><button onClick={() => download('xlsx')} disabled={exporting}>{exporting ? 'Exporting…' : 'Export XLSX'}</button></div></header><nav aria-label="Explorer">{tabs.map(t => <button key={t} aria-current={tab === t ? 'page' : undefined} onClick={() => setTab(t)}>{t[0].toUpperCase() + t.slice(1)}</button>)}</nav>{error && <p role="alert">{error}</p>}
    {tab === 'results' && <><div className="filters"><label>Scenarios<select aria-label="Scenario" value={stage} onChange={e => setStage(e.target.value)}><option value="ablation">Security only</option><option value="bridge">Original prompts</option></select></label><label>Strategy<select aria-label="Strategy" value={strategy} onChange={e => setStrategy(e.target.value)}><option>Generation</option><option>Reuse</option></select></label><label>Treatment<select aria-label="Treatment" value={treatment.id} onChange={e => setCondition(e.target.value)}>{conditions.map(c => <option key={c.id} value={c.id}>{c.contextTypes.join(' + ') || 'No security facts'} · {c.factCount} facts</option>)}</select></label><label>Tests<select aria-label="Tests" value={suite} onChange={e => setSuite(e.target.value)}><option value="security">Security</option><option value="functional">Functional</option><option value="unit">Unit</option><option value="invoked">Invoked integration</option><option value="autonomous">Autonomous integration</option><option value="all">All tests</option></select></label></div><p className="note">{plan.model} · {plan.reasoning} · Baseline: {baseline.id} · Treatment: {treatment.id}</p>{!runs.length && <p className="empty">No new evaluations imported. Rates are unreported until tests run.</p>}<Results data={data} a={a} b={b} suite={suite} /></>}
    {tab === 'runs' && <Runs data={data} runs={runs} />}{tab === 'contexts' && <Contexts data={data} />}{tab === 'conditions' && <Conditions data={data} />}
  </main>;
}
function Loader() {
  const [data, setData] = useState<Dataset>(), [error, setError] = useState('');
  useEffect(() => { fetch('data/study.json').then(async response => { if (!response.ok) throw new Error(`Cannot load study (${response.status})`); const value = await response.json(); if (value.schemaVersion !== 2) throw new Error('Unsupported study format'); setData(value); }).catch(e => setError(String(e))); }, []);
  return data ? <App data={data} /> : <main><p role={error ? 'alert' : 'status'}>{error || 'Loading…'}</p></main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><Loader /></React.StrictMode>);
