import { useState } from 'react';
import type { ComponentType } from 'react';
import type { Artifact, Dataset } from './types';

type ArtifactRenderer = ComponentType<{ artifact: Artifact; label?: string }>;
type DiffRenderer = ComponentType<{ left: Artifact | null; right: Artifact | null }>;
const definitions = [
  ['C1', 'Security surface', 'API calls, imports, formats and endpoint literals. Syntax observed; purpose and reachability unresolved.'],
  ['C2', 'Local input flows', 'Direct reads flowing through method-local variables to operations. Candidates; guards and aliases unresolved.'],
  ['C3', 'Historical audit leads', 'Automatically retrieved audit records with original review status. Retrieval does not validate a weakness.'],
  ['C4', 'Declared requirements', 'Versioned policy from the study threat model. Human-authored assumptions, automatically selected.'],
];

export function ExtractedContexts({ data, ArtifactView }: { data: Dataset; ArtifactView: ArtifactRenderer }) {
  const extraction = data.contextExtraction;
  const [type, setType] = useState('all'), [scope, setScope] = useState('feature'), [query, setQuery] = useState(''), [count, setCount] = useState(20);
  const facts = extraction.facts.filter(f => (type === 'all' || f.type === type) && (scope === 'repository' || f.scope === 'feature') && `${f.text} ${f.source.path} ${f.cwes.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="panel extraction-panel">
    <div className="section-title"><div><p className="eyebrow">AUTOMATIC EXTRACTION / VERSION 1</p><h2>145 traceable context records</h2></div><span className="context-chip security">{extraction.coverage.parsedFiles}/{extraction.coverage.sourceFiles} source files parsed</span></div>
    <div className="table-scroll"><table><thead><tr><th>Type</th><th>What the record establishes</th><th>Feature facts</th><th>Repository facts</th></tr></thead><tbody>{definitions.map(([id, name, description]) => <tr key={id}><td><strong>{id} · {name}</strong></td><td>{description}</td><td>{extraction.facts.filter(f => f.type === id && f.scope === 'feature').length}</td><td>{extraction.coverage.factsByType[id]}</td></tr>)}</tbody></table></div>
    <div className="context-filters"><select aria-label="Extracted context type" value={type} onChange={e => { setType(e.target.value); setCount(20); }}><option value="all">All four types</option>{definitions.map(([id, name]) => <option key={id} value={id}>{id} · {name}</option>)}</select><select aria-label="Extraction scope" value={scope} onChange={e => { setScope(e.target.value); setCount(20); }}><option value="feature">Highscore projection</option><option value="repository">Both game source trees</option></select><input aria-label="Search extracted facts" placeholder="Search API, source, CWE…" value={query} onChange={e => { setQuery(e.target.value); setCount(20); }} /><span>{facts.length} records</span></div>
    <div className="extracted-facts">{facts.slice(0, count).map(f => <article className="extracted-fact" key={f.id}><div className="fact-head"><span className="context-chip security">{f.type}</span><strong>{f.category.replaceAll('_', ' ')}</strong><span className="subtext">{f.status.replaceAll('_', ' ')}</span></div><p>{f.text}</p>{f.source.snippet && <pre>{f.source.snippet}</pre>}<div className="file-path">{f.source.path}{f.source.member ? ` → ${f.source.member}` : ''}{f.source.line ? `:${f.source.line}` : ''}{f.source.rule ? ` / rule: ${f.source.rule}` : ''}{f.source.record ? ` / record: ${f.source.record}` : ''}</div><div className="hash">{f.id} · source SHA-256 {f.source.sha256}</div><div className="fact-tags">{f.cwes.map(cwe => <span className="cwe" key={cwe}>{cwe}</span>)}</div></article>)}{!facts.length && <p className="empty">No extracted records match this selection. This does not establish absence of a security issue.</p>}{facts.length > count && <button className="text-button" onClick={() => setCount(count + 20)}>Show next {Math.min(20, facts.length - count)} records</button>}</div>
    <div className="prose"><details><summary>Extraction limits and exact provenance</summary>{extraction.limitations.map(l => <p key={l}>{l}</p>)}<ArtifactView artifact={extraction.artifact} label="Inspect complete extraction record" /></details></div>
    <div className="panel-foot">Repository counts include the Highscore projection. Counts measure context records, not vulnerabilities. No model outcome is used by the extractor.</div>
  </section>;
}

export function Experiments({ data, ArtifactView, DiffView }: { data: Dataset; ArtifactView: ArtifactRenderer; DiffView: DiffRenderer }) {
  const plan = data.experimentPlans[0];
  const [chosen, setChosen] = useState(plan.conditions.find(c => c.id === 'generation_security_all')!.id);
  const selected = plan.conditions.find(c => c.id === chosen)!;
  const baseline = plan.conditions.find(c => c.stage === selected.stage && c.strategy === selected.strategy && c.factCount === 0)!;
  return <><div className="page-intro compact"><div><p className="eyebrow">PROSPECTIVE STUDY / FROZEN DESIGN</p><h1>Luna experiment plan</h1><p className="lede">Inspect every condition, context record and exact prompt before model execution.</p></div><span className="study-label">Planned · no observations published</span></div>
    <div className="metrics">{[['Model', plan.model, `${plan.reasoning} reasoning · temperature omitted`], ['Bridge attempts', '20', '4 exact historical prompts × 5 repetitions'], ['Ablation attempts', '120', '6 selections × 2 strategies × 10 repetitions'], ['Context types', '4', 'C1, C2, C3, C4 and their union']].map(([label, value, detail]) => <div className="metric plan-metric" key={label}><div>{label}</div><strong>{value}</strong><small>{detail}</small></div>)}</div>
    <div className="notice">{plan.analysis.sampleCaveat} Transport completion will remain separate from functional and security outcomes.</div>
    <section className="panel"><div className="section-title"><div><p className="eyebrow">16 CONDITIONS / 140 PLANNED ATTEMPTS</p><h2>Context budget and exact intervention</h2></div></div><div className="table-scroll"><table><thead><tr><th>Condition</th><th>Base context</th><th>Security types</th><th>Facts</th><th>Prompt characters</th><th>Planned n</th></tr></thead><tbody>{plan.conditions.map(c => <tr key={c.id} className={chosen === c.id ? 'selected-condition' : ''}><td><button className="text-button" aria-label={`Inspect planned ${c.id}`} onClick={() => setChosen(c.id)}>{c.id}</button><span className="subtext">{c.stage} · {c.strategy}</span></td><td>{c.baseContext}</td><td>{c.contextTypes.join(' + ') || 'No security facts'}</td><td>{c.factCount}</td><td>{c.promptCharacters.toLocaleString('en-GB')}</td><td>{c.repetitions}</td></tr>)}</tbody></table></div><div className="panel-foot">Prompt token counts remain unmeasured until the provider reports them. Characters and bytes are measured exactly; facts have different lengths.</div></section>
    <section className="panel"><div className="section-title"><div><p className="eyebrow">SELECTED CONDITION / {selected.stage}</p><h2>{selected.id}</h2></div><span className="context-chip">{selected.factCount} context records</span></div><div className="prose"><p>Injection: {plan.injection}. Scope: Highscore filename projection. Comparison: {baseline.id}.</p><p>{selected.stage === 'bridge' ? 'The bridge preserves the exact archived payload, including its original structural/functional/behavioral context and output instructions.' : 'All ablation arms share the same no-context task, source attachments, threat-model disclosure and output instructions. Only the selected security records vary.'}</p><details><summary>Exact selected fact IDs ({selected.factCount})</summary>{selected.factIds.map(id => <p key={id}><code>{id}</code> · {data.contextExtraction.facts.find(f => f.id === id)?.text ?? data.facts.find(f => f.id === id)?.text}</p>)}</details><ArtifactView artifact={selected.prompt} label="Inspect complete frozen prompt" /></div><DiffView left={baseline.prompt} right={selected.prompt} /></section>
    <section className="panel prose"><p className="eyebrow">ANALYSIS AND SCHEDULE</p><h2>Primary endpoint and comparison boundaries</h2><p>{plan.analysis.primary}</p><p>{plan.analysis.confounds}</p><p>{plan.analysis.controls}</p><p>{plan.analysis.timing} Scheduling seed: {plan.scheduleSeed}.</p><details><summary>Randomized execution schedule ({plan.schedule.length} planned attempts)</summary><div className="table-scroll"><table><thead><tr><th>Order</th><th>Attempt</th><th>Status</th></tr></thead><tbody>{plan.schedule.map((r, i) => <tr key={r.runId}><td>{i + 1}</td><td>{r.runId}</td><td>{r.status}</td></tr>)}</tbody></table></div></details><ArtifactView artifact={plan.artifact} label="Inspect frozen experiment manifest" /></section>
  </>;
}
