#!/usr/bin/env python3
"""Assemble docs/RESULTS.md from the N-family reconciled audit artifacts.

Pure formatter over reconciled.json / taxonomy.json / family_stats.json /
sink_census.json. Narrative lives in REPORT.md (hand-written); this only renders
numbers so they cannot drift from the data.
"""
import json
import pathlib
import collections

B = pathlib.Path(__file__).resolve().parents[1]
FIND = B / "audit" / "findings"

FAMILY_LABEL = {
    "oxa": "ox-alpha", "codex": "gpt-5.6-sol (max)", "glm": "GLM-5.3 *",
    "kimi": "Kimi-k3 *", "qwen": "Qwen3.8-max", "minimax": "MiniMax-m3 *",
}


def load(name):
    return json.loads((FIND / name).read_text())


def sev_key(s):
    return {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(str(s).lower(), 9)


def main():
    reconciled = load("reconciled.json")
    taxonomy = load("taxonomy.json")
    census = load("sink_census.json")
    raw = load("all_findings.json")
    fam_stats = load("family_stats.json")

    fams = collections.Counter(f["_family"] for f in raw)
    consensus = [r for r in reconciled if r["tier"] == "CONSENSUS"]
    corrob = [r for r in reconciled if r["tier"] == "CORROBORATED"]

    L = []
    L.append("# Results — Apo-Games security audit (multi-model)\n")
    L.append("_Auto-generated by `scripts/gen_report.py`. Do not hand-edit; regenerate._\n")
    L.append("_`*` = open-weight model (the guideline-#6 baseline)._\n")

    L.append("## Coverage\n")
    L.append(f"- Corpus: **{census['corpus_files']}** `.java` files across the normalized variants.")
    L.append(f"- **{len([k for k in fams])} auditor families** produced findings; "
             f"raw findings per family: "
             + ", ".join(f"{FAMILY_LABEL.get(k,k)} {v}" for k, v in
                         sorted(fams.items(), key=lambda kv: -kv[1])) + ".")
    L.append(f"- Total raw findings: **{len(raw)}** → **{len(reconciled)}** distinct issues → "
             f"**{len(consensus)}** consensus (≥4 families agree) + "
             f"**{len(corrob)}** corroborated (2–3 families).\n")

    L.append("## Per-family reliability\n")
    L.append("A model's finding is _backed_ when at least one other family independently "
             "reported the same (variant, file, category). Low backing ⇒ more idiosyncratic "
             "(or more hallucinated) findings.\n")
    L.append("| Family | Variants audited | Raw findings | Distinct groups | Backed by ≥1 other | Backed % |")
    L.append("|---|--:|--:|--:|--:|--:|")
    for fam, s in sorted(fam_stats.items(),
                         key=lambda kv: -kv[1]["distinct_groups_touched"]):
        g = s["distinct_groups_touched"]
        pct = f"{100*s['groups_backed_by_others']/g:.0f}%" if g else "—"
        L.append(f"| {FAMILY_LABEL.get(fam, fam)} | {s['variants_audited']} | {s['raw_findings']} "
                 f"| {g} | {s['groups_backed_by_others']} | {pct} |")

    L.append("\n## Category taxonomy\n")
    L.append("| Category | Variants | Consensus (≥4) | Corroborated (2–3) | Single | Max clone spread |")
    L.append("|---|--:|--:|--:|--:|--:|")
    for t in taxonomy:
        L.append(f"| {t['category']} | {t['variants_affected']} | {t['consensus']} "
                 f"| {t['corroborated']} | {t['single_source']} | {t['max_clone_spread']} |")

    L.append("\n## Consensus findings (≥4 independent families agree)\n")
    L.append("| Agree | Sev | Category | Variant | File | Clones | CWE | Title |")
    L.append("|--:|---|---|---|---|--:|---|---|")
    for r in sorted(consensus, key=lambda r: (-r["agreement"], sev_key(r["severity"]))):
        title = (r.get("title") or "").replace("|", "/")[:70]
        L.append(f"| {r['agreement']}/{r['audited_by']} | {r['severity']} | {r['category']} "
                 f"| {r['variant']} | {r['file']} | {r['clone_variants']} | {r.get('cwe','')} | {title} |")

    L.append("\n## Corroborated findings (2–3 families)\n")
    L.append("| Agree | Sev | Category | Variant | File | Clones | Families |")
    L.append("|--:|---|---|---|---|--:|---|")
    for r in sorted(corrob, key=lambda r: (sev_key(r["severity"]), -r["clone_variants"])):
        L.append(f"| {r['agreement']}/{r['audited_by']} | {r['severity']} | {r['category']} "
                 f"| {r['variant']} | {r['file']} | {r['clone_variants']} | {','.join(r['families'])} |")

    L.append("\n## Deterministic sink census (context, not findings)\n")
    L.append("| Sink category | Total hits | Variants |")
    L.append("|---|--:|--:|")
    for name, c in sorted(census["categories"].items(), key=lambda kv: -kv[1]["total_hits"]):
        if c["total_hits"]:
            L.append(f"| {name} | {c['total_hits']} | {c['variants_hit']} |")

    (B / "docs" / "RESULTS.md").write_text("\n".join(L) + "\n")
    print(f"wrote docs/RESULTS.md | families={len(fams)} consensus={len(consensus)} "
          f"corroborated={len(corrob)} distinct={len(reconciled)}")


if __name__ == "__main__":
    main()
